[package]
name = "delay-cmd"
version = "0.1.0"
authors = ["Keith Stouffer <kjstouffer@users.noreply.github.com>"]
build = "build.rs"

[dependencies]
clap = "2.31.2"

[build-dependencies]
clap = "2.31.2"

